import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/page";
import Footer from "@/components/Footer/page";
import { Kanit } from "next/font/google";

const kanit = Kanit({ subsets: ["latin"], weight: ["300", "400", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      {/* ✅ Corrigido: interpolação da classe com Template Literal */}
      <body className={`${kanit.className} flex flex-col h-screen`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
